### ISSUE TITLE
offeringlist alles offen

### ISSUE THREAD

**Issue by mportz** [Aufklaerwerk/aufklaerwerk-vue#35]
Wenn man die Suche benutzt, auf ein Angebot klickt und dann zurück geht bekommt man alle offerings  (https://www.aufklaerwerk.org/searcher#offer-list) angezeigt und nicht nur die die davor in den Suchergebnissen waren. Denke hier müssten wir mit cookies arbeiten.

**Comment by Schuetzlito** [comment]
Fehler tritt nicht mehr auf.
