### ISSUE TITLE
autocomplete location search

### ISSUE THREAD

**Issue by mportz** [Aufklaerwerk/aufklaerwerk-vue#45]
Für die Suchmaske wäre es von Vorteil, die möglichen Locations nicht über die Datenbank zu füllen, sondern eine Freitextsuche mti Location-Autocomplete anzubieten.

Hierzu gäbe es bspw. die folgenden Optionen:
- https://developers.google.com/maps/documentation/places/web-service/autocomplete
- https://motis-project.de/docs/features/autocomplete.html#autocompletion-of-addresses-and-station-names
- https://www.geoapify.com/address-autocomplete

**Comment by Schuetzlito** [comment]
wurde bereits übertragen ins Trelloboard.
