### ISSUE TITLE
reset radius when deselecting location

### ISSUE THREAD

**Issue by mportz** [Aufklaerwerk/aufklaerwerk-vue#46]
Wenn man aktuell in der Suchmaske eine Stadt auswählt und den Radius setzt und anschließend die Stadt wieder löscht, wird der Radius beibehalten und man kann ihn nicht mehr anpassen.
![image](https://user-images.githubusercontent.com/74604123/196464941-e86fb46f-7f2a-42dc-bdf9-f59f88207c48.png)
Wir sollten das ggf. so anpassen, dass der Radius in diesem Fall wieder auf 0 zurückgesetzt wird. Wird nur ein neuer Ort ausgewählt, sollte er denke ich aber beibehalten werden.

**Comment by Schuetzlito** [comment]
ist hinfällig. Radius wird nicht mehr deselected und kann jederzeit geändert werden.
